# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: '{{version}}'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish_helium_flutter:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/helium_flutter

  publish_helium_revenuecat:
    needs: publish_helium_flutter
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/helium_revenuecat
